---
# tasks file for k8s-slave

- name: "Installing docker"
  package:
    name: docker
    state: present

- name: "Starting docker services"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Configuring yum repository"
  yum_repository:
    name: kubernetes
    description: kubernetes.repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: >-
            https://packages.cloud.google.com/yum/doc/yum-key.gpg
            https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: "Installing Softwares"
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop:
    - iproute-tc
    - kubelet
    - kubeadm
    - kubectl

- name: "Starting services"
  service:
    name: "kubelet"
    state: started
    enabled: yes
  
- name: "Pulling images"
  shell: "kubeadm config images pull"
  changed_when: false

- name: "Changing driver in docker"
  copy:
    content: |
            {
               "exec-opts": ["native.cgroupdriver=systemd"]
            }
    dest: /etc/docker/daemon.json
  register: z

- name: "Restarting docker"
  service:
    name: docker
    state: restarted 
  when: z.changed == true

- name: "Updating config file"
  copy: 
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1

- name: "Changing parameters for kernel"
  command: "sysctl --system"

- name: "Create file"
  file:
    path: /root/token
    state: touch
    mode: '0644'
    
- copy:
    src: /tmp/token
    dest: /root/token
    
- name: "Join to cluster"
  shell: "bash /root/token"
  ignore_errors: yes
